/* This file was generated by gen_romdb.py */
/* Games that use 16Kbit EEPROM */
static const uint64_t lut_ee16k[] = {
   0x975B7845A2505C18ULL, /* 77a Special Edition by Count0 (PD) */
   0x514B6900B4B19881ULL, /* Banjo to Kazooie no Daibouken 2 (J) [!] */
   0x155B7CDFF0DA7325ULL, /* Banjo-Tooie (A) [!] */
   0xC9176D39EA4779D1ULL, /* Banjo-Tooie (E) (M4) [!] */
   0xC2E9AA9A475D70AAULL, /* Banjo-Tooie (U) [!] */
   0x373F58899A6CA80AULL, /* Conker's Bad Fur Day (E) [!] */
   0x30C7AC507704072DULL, /* Conker's Bad Fur Day (U) [!] */
   0x83F3931ECB72223DULL, /* Cruis'n World (E) [!] */
   0xDFE61153D76118E6ULL, /* Cruis'n World (U) [!] */
   0x11936D8C6F2C4B43ULL, /* Donkey Kong 64 (E) [!] */
   0x053C89A7A5064302ULL, /* Donkey Kong 64 (J) [!] */
   0x0DD4ABABB5A2A91EULL, /* Donkey Kong 64 (U) (Kiosk Demo) [!] */
   0xEC58EABFAD7C7169ULL, /* Donkey Kong 64 (U) [!] */
   0xB6306E99B63ED2B2ULL, /* Doraemon 2 - Nobita to Hikari no Shinden (J) [!] */
   0xA8275140B9B056E8ULL, /* Doraemon 3 - Nobita no Machi SOS! (J) [!] */
   0x202A8EE483F88B89ULL, /* Excitebike 64 (E) [!] */
   0x861C3519F6091CE5ULL, /* Excitebike 64 (J) [!] */
   0xAF754F7B1DD17381ULL, /* Excitebike 64 (U) (Kiosk Demo) [!] */
   0x07861842A12EBC9FULL, /* Excitebike 64 (U) [!] */
   0x1739EFBAD0B43A68ULL, /* Kobe Bryant in NBA Courtside (E) [!] */
   0x616B84948A509210ULL, /* Kobe Bryant's NBA Courtside (U) [!] */
   0xA197CB527520DE0EULL, /* Madden Football 64 (E) [!] */
   0x13836389265B3C76ULL, /* Madden Football 64 (U) [!] */
   0xC56741600F5F453CULL, /* Mario Party 3 (E) (M4) [!] */
   0x0B0AB4CD7B158937ULL, /* Mario Party 3 (J) [!] */
   0x7C3829D96E8247CEULL, /* Mario Party 3 (U) [!] */
   0x839F3AD5406D15FAULL, /* Mario Tennis (E) [!] */
   0x5001CF4FF30CB3BDULL, /* Mario Tennis (U) [!] */
   0x3A6C42B51ACADA1BULL, /* Mario Tennis 64 (J) [!] */
   0x147E0EDB36C5B12CULL, /* Neon Genesis Evangelion (J) [!] */
   0xF468118CE32EE44EULL, /* PD Ultraman Battle Collection 64 (J) [!] */
   0xE4B08007A602FF33ULL, /* Perfect Dark (E) (M5) [!] */
   0x96747EB4104BB243ULL, /* Perfect Dark (J) [!] */
   0xDDF460CC3CA634C0ULL, /* Perfect Dark (U) (V1.0) [!] */
   0x41F2B98FB458B466ULL, /* Perfect Dark (U) (V1.1) [!] */
   0xFEE970104E94A9A0ULL, /* RR64 - Ridge Racer 64 (E) [!] */
   0x2500267E2A7EC3CEULL, /* RR64 - Ridge Racer 64 (U) [!] */
   0x53ED2DC406258002ULL, /* Star Wars Episode I - Racer (E) (M3) [!] */
   0x61F5B152046122ABULL, /* Star Wars Episode I - Racer (J) [!] */
   0x72F703986556A98BULL, /* Star Wars Episode I - Racer (U) [!] */
   0x2DCFCA608354B147ULL, /* Yoshi Story (J) [!] */
   0xD3F97D496924135BULL, /* Yoshi's Story (E) (M3) [!] */
   0x2337D8E86B8E7CECULL  /* Yoshi's Story (U) (M2) [!] */
};

/* (Delay SI) */
static const uint64_t lut_delaysi[][2] = {
   { 0xC2E9AA9A475D70AAULL, 0 }, 
   { 0xC9176D39EA4779D1ULL, 0 },
   { 0x155B7CDFF0DA7325ULL, 0 },
};

/* Cycles per emulated instruction (aka CountPerOp) */
static const uint64_t lut_cpop[][2] = {
   { 0xB98BA4565B2B76AFULL, 1 }, /* 64 de Hakken!! Tamagotchi Minna de Tamagotchi World (J) [!] */
   { 0x9C961069F5EA488DULL, 1 }, /* 64 Oozumou (J) [!] */
   { 0x27C425D08C2D99C1ULL, 1 }, /* Airboarder 64 (E) [!] */
   { 0x6C45B60CDCE50E30ULL, 1 }, /* Airboarder 64 (J) [!] */
   { 0xB088FBB4441E4B1DULL, 1 }, /* Bass Hunter 64 (E) [!] */
   { 0xD76333AC0CB6219DULL, 1 }, /* Bass Rush - ECOGEAR PowerWorm Championship (J) [!] */
   { 0xBCFACCAAB814D8EFULL, 1 }, /* Bassmasters 2000 (U) [!] */
   { 0x6AA4DDE7E3E2F4E7ULL, 3 }, /* BattleTanx (U) [!] */
   { 0x75A4E2476008963DULL, 3 }, /* BattleTanx - Global Assault (U) [!] */
   { 0xA1B64A61D014940BULL, 3 }, /* Beetle Adventure Racing! (E) (M3) [!] */
   { 0x7EAE24889D40A35AULL, 1 }, /* Biohazard 2 (J) [!] */
   { 0x0B58B8CDB7B291D2ULL, 1 }, /* Body Harvest (E) (M3) [!] */
   { 0x5326696FFE9A99C3ULL, 1 }, /* Body Harvest (U) [!] */
   { 0x8F12C09645DC17E1ULL, 1 }, /* Bug's Life, A (E) [!] */
   { 0x2B38AEC06350B810ULL, 1 }, /* Bug's Life, A (F) [!] */
   { 0xDFF227D90D4D8169ULL, 1 }, /* Bug's Life, A (G) [!] */
   { 0xF63B89CE4582D57DULL, 1 }, /* Bug's Life, A (I) [!] */
   { 0x82DC04FDCF2D82F4ULL, 1 }, /* Bug's Life, A (U) [!] */
   { 0xAC16400ECF5D071AULL, 1 }, /* California Speed (U) [!] */
   { 0x580162ECE3108BF1ULL, 1 }, /* Carmageddon 64 (E) (M4) (Eng-Spa-Fre-Ger) [!] */
   { 0xE48E01F5E6E51F9BULL, 1 }, /* Carmageddon 64 (E) (M4) (Eng-Spa-Fre-Ita) [!] */
   { 0xF00F2D4E340FAAF4ULL, 1 }, /* Carmageddon 64 (U) [!] */
   { 0xFB3C48D08D28F69FULL, 1 }, /* Charlie Blast's Territory (E) [!] */
   { 0x1E0E96E84E28826BULL, 1 }, /* Charlie Blast's Territory (U) [!] */
   { 0xF8009DB06B291823ULL, 1 }, /* City-Tour GP - Zennihon GT Senshuken (J) [!] */
   { 0x630AA37D896BD7DBULL, 1 }, /* Destruction Derby 64 (E) (M3) [!] */
   { 0xDEE584A20F161187ULL, 1 }, /* Destruction Derby 64 (U) [!] */
   { 0xC16C421BA21580F7ULL, 3 }, /* Disney's Donald Duck - Goin' Quackers (U) [!] */
   { 0xD614E5BFA76DBCC1ULL, 1 }, /* Disney's Tarzan (E) [!] */
   { 0x001A3BD0AFB3DE1AULL, 1 }, /* Disney's Tarzan (F) [!] */
   { 0x4C2613234F295E1AULL, 1 }, /* Disney's Tarzan (G) [!] */
   { 0xCBFE69C7F2C0AB2AULL, 1 }, /* Disney's Tarzan (U) [!] */
   { 0x3DF17480193DED5AULL, 3 }, /* Donald Duck - Quack Attack (E) (M5) [!] */
   { 0x11936D8C6F2C4B43ULL, 1 }, /* Donkey Kong 64 (E) [!] */
   { 0x053C89A7A5064302ULL, 1 }, /* Donkey Kong 64 (J) [!] */
   { 0x0DD4ABABB5A2A91EULL, 1 }, /* Donkey Kong 64 (U) (Kiosk Demo) [!] */
   { 0xEC58EABFAD7C7169ULL, 1 }, /* Donkey Kong 64 (U) [!] */
   { 0xFBB9F1FA6BF88689ULL, 1 }, /* Duck Dodgers Starring Daffy Duck (U) (M3) [!] */
   { 0xDC36626A3F3770CBULL, 1 }, /* Duke Nukem - ZER0 H0UR (E) [!] */
   { 0x32CA974BB2C29C50ULL, 1 }, /* Duke Nukem - ZER0 H0UR (F) [!] */
   { 0x04DAF07F0D18E688ULL, 1 }, /* Duke Nukem - ZER0 H0UR (U) [!] */
   { 0x202A8EE483F88B89ULL, 1 }, /* Excitebike 64 (E) [!] */
   { 0x07861842A12EBC9FULL, 1 }, /* Excitebike 64 (U) [!] */
   { 0x66CF0FFEAD697F9CULL, 1 }, /* Fighting Force 64 (E) [!] */
   { 0x32EFC7CBC3EA3F20ULL, 1 }, /* Fighting Force 64 (U) [!] */
   { 0x22E9623FB60E52ADULL, 1 }, /* Flying Dragon (E) [!] */
   { 0xA92D52E51D26B655ULL, 1 }, /* Flying Dragon (U) [!] */
   { 0xF774EAEEF0D8B13EULL, 1 }, /* Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou! (J) [!] */
   { 0xEE4A0E338FD588C9ULL, 1 }, /* GT 64 - Championship Edition (E) (M3) [!] */
   { 0xC49ADCA2F1501B62ULL, 1 }, /* GT 64 - Championship Edition (U) [!] */
   { 0x95A80114E0B72A7FULL, 1 }, /* Hamster Monogatari 64 (J) [!] */
   { 0x775AFA9C0EB52EF6ULL, 1 }, /* Hard Coded Demo by Silo and Fractal (PD) [a1] */
   { 0x98DF9DFC6606C189ULL, 1 }, /* Harvest Moon 64 (U) [!] */
   { 0xAE90DBEB79B89123ULL, 1 }, /* Hercules - The Legendary Journeys (E) (M6) [!] */
   { 0x7F3CEB778981030AULL, 1 }, /* Hercules - The Legendary Journeys (U) [!] */
   { 0x95B2B30B2B6415C1ULL, 1 }, /* Hexen (E) [!] */
   { 0x5C1B5FBD7E961634ULL, 1 }, /* Hexen (F) [!] */
   { 0x9AB3B50ABC666105ULL, 1 }, /* Hexen (G) [!] */
   { 0x66751A5754A29D6EULL, 1 }, /* Hexen (J) [!] */
   { 0x35FF8F1A6E79E3BEULL, 1 }, /* Hiryuu no Ken Twin (J) [!] */
   { 0x72611D7D9919BDD2ULL, 3 }, /* HSV Adventure Racing (A) [b1] */
   { 0xB58988E9B1FC4BE8ULL, 1 }, /* Hydro Thunder (E) [!] */
   { 0x29A045CEABA9060EULL, 1 }, /* Hydro Thunder (F) [!] */
   { 0xC8DC65EB3D8C8904ULL, 1 }, /* Hydro Thunder (U) [!] */
#ifndef GLES
   { 0x979B263EF8470004ULL, 1 }, /* Killer Instinct Gold (E) [!] */
   { 0x9E8FE2BA8B270770ULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [!] */
   { 0xCB06B744633194DBULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [b1][t1] */
   { 0x06CB44B73163DB94ULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [b2] */
   { 0x9E8FE2BA8B270770ULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [o1] */
   { 0x06CB44B73163DB94ULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [t1] */
   { 0xCB06B744633194DBULL, 1 }, /* Killer Instinct Gold (U) (V1.0) [t2] */
   { 0x9E8FCDFA49F5652BULL, 1 }, /* Killer Instinct Gold (U) (V1.1) [!] */
   { 0xF908CA4C36464327ULL, 1 }, /* Killer Instinct Gold (U) (V1.2) [!] */
   { 0x06CB44B73163DB94ULL, 1 }, /* Killer Instinct Gold (U) (V1.2) [b1] */
   { 0xF908CA4C36464327ULL, 1 }, /* Killer Instinct Gold (U) (V1.2) [o1] */
#endif
   { 0x8C138BE095700E46ULL, 1 }, /* In-Fisherman Bass Hunter 64 (U) [!] */
   { 0xE2D37CF0F57E4EAEULL, 1 }, /* International Superstar Soccer 64 (E) [!] */
   { 0x5F2763C462412AE5ULL, 1 }, /* International Superstar Soccer 64 (U) [!] */
   { 0x6EDD4766A93E9BA8ULL, 3 }, /* Jikkyou Powerful Pro Yakyuu - Basic Han 2001 (J) [!] */
   { 0xE0A79F8C32CC97FAULL, 1 }, /* Jikkyou World Soccer 3 (J) [!] */
   { 0xF478D8B39716DD6DULL, 3 }, /* LEGO Racers (E) (M10) [!] */
   { 0x096A40EA8ABE0A10ULL, 3 }, /* LEGO Racers (U) (M10) [b1] */
   { 0xFBB9F1FA6BF88689ULL, 1 }, /* Lt. Duck Dodgers (Prototype) */
   { 0x0CB816865FD85A81ULL, 1 }, /* Madden NFL 2000 (U) [!] */
   { 0xEB38F792190EA246ULL, 1 }, /* Madden NFL 2001 (U) [!] */
   { 0xD7134F8DC11A00B5ULL, 1 }, /* Madden NFL 2002 (U) [!] */
   { 0x3925D6258C83C75EULL, 1 }, /* Madden NFL 99 (E) [!] */
   { 0xDEB78BBA52F6BD9DULL, 1 }, /* Madden NFL 99 (U) [!] */
   { 0x9C66306980F24A80ULL, 1 }, /* Mario Party (E) (M3) [!] */
   { 0xADA815BE6028622FULL, 1 }, /* Mario Party (J) [!] */
   { 0x2829657EA0621877ULL, 1 }, /* Mario Party (U) [!] */
   { 0x82380387DFC744D9ULL, 1 }, /* Mario Party 2 (E) (M5) [!] */
   { 0xED567D0F38B08915ULL, 1 }, /* Mario Party 2 (J) [!] */
   { 0x9EA95858AF72B618ULL, 1 }, /* Mario Party 2 (U) [!] */
   { 0xC56741600F5F453CULL, 1 }, /* Mario Party 3 (E) (M4) [!] */
   { 0x0B0AB4CD7B158937ULL, 1 }, /* Mario Party 3 (J) [!] */
   { 0x7C3829D96E8247CEULL, 1 }, /* Mario Party 3 (U) [!] */
   { 0x3BA7CDDC464E52A0ULL, 1 }, /* Mario Story (J) [!] */
   { 0x5AC383E1D712E387ULL, 1 }, /* Monopoly (U) [!] */
   { 0xD3D806FCB43AA2A8ULL, 3 }, /* Monster Truck Madness 64 (E) (M5) [!] */
   { 0xB19AD9997E585118ULL, 3 }, /* Monster Truck Madness 64 (U) [!] */
   { 0x7F9345D3841ECADEULL, 1 }, /* Mystical Ninja 2 Starring Goemon (E) (M3) [!] */
   { 0xA292524F3D6C2A49ULL, 1 }, /* NBA In the Zone '99 (U) [!] */
   { 0x3FFE80F4A7C15F7EULL, 1 }, /* NBA Showtime - NBA on NBC (U) [!] */
   { 0x2857674DCC4337DAULL, 1 }, /* Nightmare Creatures (U) [!] */
   { 0xCD3C3CDF317793FAULL, 1 }, /* Nintama Rantarou 64 Game Gallery (J) [!] */
   { 0x8A97A197272DF6C1ULL, 1 }, /* Nuclear Strike 64 (E) (M2) [!] */
   { 0x8F50B845D729D22FULL, 1 }, /* Nuclear Strike 64 (G) [!] */
   { 0x4998DDBBF7B7AEBCULL, 1 }, /* Nuclear Strike 64 (U) [!] */
   { 0xD83BB920CC406416ULL, 1 }, /* Nushi Tsuri 64 (J) [!] */
   { 0x19AB29AFC71BCD28ULL, 1 }, /* Paper Mario (E) (M4) [!] */
   { 0x65EEE53AED7D733CULL, 1 }, /* Paper Mario (U) [!] */
   { 0x1AA05AD546F52D80ULL, 3 }, /* Pilotwings 64 (E) (M3) [!] */
   { 0x09CC4801E42EE491ULL, 3 }, /* Pilotwings 64 (J) [!] */
   { 0xC851961C78FCAAFAULL, 3 }, /* Pilotwings 64 (U) [!] */
   { 0x9BA10C4E0408ABD3ULL, 1 }, /* Pro Mahjong Kiwame 64 (J) [!] */
   { 0x1BDCB30FA132D876ULL, 1 }, /* Pro Mahjong Tsuwamono 64 - Jansou Battle ni Chousen (J) [!] */
   { 0x7433D9D72C4322D0ULL, 1 }, /* Quake II (E) [!] */
   { 0xBDA8F143B1AF2D62ULL, 1 }, /* Quake II (U) [!] */
   { 0x3918834A15B50C29ULL, 1 }, /* Razor Freestyle Scooter (U) [!] */
   { 0xE921953313FBAFBDULL, 1 }, /* Ready 2 Rumble Boxing - Round 2 (U) [!] */
   { 0x9B500E8EE90550B3ULL, 1 }, /* Resident Evil 2 (E) (M2) [!] */
   { 0xAA18B1A507DB6AEBULL, 1 }, /* Resident Evil 2 (U) (V1.1) [!] */
   { 0x02D8366A6CABEF9CULL, 3 }, /* Road Rash 64 (E) [!] */
   { 0xF050746C247B820BULL, 3 }, /* Road Rash 64 (U) [!] */
   { 0x0B6B4DDB9671E682ULL, 1 }, /* Roadsters Trophy (U) (M3) [!] */
   { 0xB7CF2136FA0AA715ULL, 1 }, /* Rush 2 - Extreme Racing USA (E) (M6) [!] */
   { 0xEDD6E03168136013ULL, 1 }, /* Rush 2 - Extreme Racing USA (U) [!] */
   { 0x51D29418D5B46AE3ULL, 1 }, /* San Francisco Rush 2049 (E) (M6) [!] */
   { 0xB9A9ECA217AAE48EULL, 1 }, /* San Francisco Rush 2049 (U) [!] */
   { 0x60C437E5A2251EE3ULL, 1 }, /* Shadow Man (E) (M3) [!] */
   { 0xEA06F8C307C2DEEDULL, 1 }, /* Shadow Man (F) [!] */
   { 0x84D5FD75BBFD3CDFULL, 1 }, /* Shadow Man (G) [!] */
   { 0x3A4760B52D74D410ULL, 1 }, /* Shadow Man (U) [!] */
   { 0xD137A2CA62B65053ULL, 1 }, /* Shigesato Itoi's No. 1 Bass Fishing! Definitive Edition (J) [!] */
   { 0xA3A044B56DB1BF5EULL, 1 }, /* Spacer by Memir (POM '99) (PD) */
   { 0xE0C4F72F769E1506ULL, 1 }, /* Tigger's Honey Hunt (E) (M7) [!] */
   { 0x4EBFDD33664C9D84ULL, 1 }, /* Tigger's Honey Hunt (U) [!] */
   { 0xCCEB385826952D97ULL, 1 }, /* Toy Story 2 (E) [!] */
   { 0xCB93DB977F5C63D5ULL, 1 }, /* Toy Story 2 (F) [!] */
   { 0x782A9075E552631DULL, 1 }, /* Toy Story 2 (G) [!] */
   { 0xA150743ECF2522CDULL, 1 }, /* Toy Story 2 (U) [!] */
   { 0xFE4B6B43081D29A7ULL, 1 }, /* Triple Play 2000 (U) [!] */
   { 0x28D5562DE4D5AE50ULL, 1 }, /* Uchhannanchan no Hono no Challenger - Denryu IraIra Bou (J) [!] */
   { 0x151F79F48EEDC8E5ULL, 1 }, /* Vigilante 8 (E) [!] */
   { 0xE2BC82A2591CD694ULL, 1 }, /* Vigilante 8 (F) [!] */
   { 0x6EDA5178D396FEC1ULL, 1 }, /* Vigilante 8 (G) [!] */
   { 0xEA71056AE4214847ULL, 1 }, /* Vigilante 8 (U) [!] */
   { 0xDD10BC7EF900B351ULL, 1 }, /* Vigilante 8 - 2nd Offence (E) [!] */
   { 0xF5C5866D052713D9ULL, 1 }, /* Vigilante 8 - 2nd Offense (U) [!] */
   { 0x98F9F2D003D9F09CULL, 1 }, /* Virtual Pool 64 (E) [!] */
   { 0x4E4A7643A37439D7ULL, 1 }, /* Virtual Pool 64 (U) [!] */
   { 0xD715CC70271CF5D6ULL, 1 }, /* War Gods (E) [!] */
   { 0xF7FE28F6C3F2ACC3ULL, 1 }, /* War Gods (U) [!] */
   { 0x535DF3E2609789F1ULL, 3 }, /* Wave Race 64 - Shindou Edition (J) (V1.2) [!] */
   { 0xD4C45A1AF425B25EULL, 3 }, /* WCW Nitro (U) [!] */
   { 0x68E8A8750CE7A486ULL, 1 }, /* WCW-nWo Revenge (E) [!] */
   { 0xDEE596ABAF3B7AE7ULL, 1 }, /* WCW-nWo Revenge (U) [!] */
   { 0xCEA8B54F7F21D503ULL, 3 }, /* Wetrix (E) (M6) [!] */
   { 0xDCB6EAFAC6BBCFA3ULL, 3 }, /* Wetrix (J) [!] */
   { 0x54310E7D6B5430D8ULL, 1 }, /* Wipeout 64 (E) [!] */
   { 0x132D2732C70E9118ULL, 1 }, /* Wipeout 64 (U) [!] */
};
