/* This file was generated by gen_romdb.py */

/* Games that need alternate VI timing */
/* Games that use 16Kbit EEPROM */

/* Games that use 4Kbit EEPROM */
/* Games that use Flash RAM */
/* (Delay SI) */
/* Title-wide overrides keyed on the cartridge ID; see the lut_cart_save
 * provenance comment for the scheme.  Hash-keyed predecessors of these
 * tables listed individual releases; every title here carried the same
 * value across all of its releases. */
static const char lut_alternate_vi_id[][4] = {
   "NPN", /* Pokemon Puzzle League */
};

static const char lut_vi_clock_1500_id[][4] = {
   "NPN", /* Pokemon Puzzle League */
};

static const char lut_vi_clock_1600_id[][4] = {
   "NSB", /* Twisted Edge / King Hill 64 - Extreme Snowboarding */
};

static const char lut_vi_clock_2200_id[][4] = {
   "NB5", /* Biohazard 2 (J) */
   "NIJ", /* Indiana Jones and the Infernal Machine */
   "NRE", /* Resident Evil 2 */
};

/* Games that read back parallel-rdp rendered frames from RDRAM during
 * normal play and therefore require synchronous RDP. In asynchronous
 * mode the CPU never waits on the GPU timeline, the readback sees stale
 * data and the game soft-locks (Resident Evil 2 stops at the N64 logo
 * and never starts the intro FMV). */
static const char lut_parallel_sync_id[][4] = {
   "NB5", /* Biohazard 2 (J) */
   "NRE", /* Resident Evil 2 */
};

static const char lut_fixedaudiopos_id[][4] = {
   "NSB", /* Twisted Edge / King Hill 64 - Extreme Snowboarding */
};

static const struct cart_delaysi_entry { char id[4]; unsigned char delaysi; } lut_delaysi_id[] = {
   { "NB7", 0 }, /* Banjo-Tooie / Banjo to Kazooie no Daibouken 2 */
   { "NTM", 0 }, /* Mischief Makers / Yuke Yuke!! Trouble Makers */
   { "NYK", 0 }, /* Yakouchuu II - Satsujin Kouro */
};

/* Header-CRC delay-SI remainder: build-specific overrides a cartridge ID
 * cannot express, since the affected build shares its id with releases
 * that must keep the default.  The Super Mario 64 60fps V2 hack's
 * per-frame controller polling bypasses the SI access arbitration, so
 * its in-game save races the EEPROM transaction's SI completion event
 * and loses the wakeup when completion is delayed -- the save thread
 * then sleeps forever in osRecvMesg.  Immediate completion closes the
 * window; the shared NSM id rules out a title-wide entry, as vanilla
 * SM64 must keep the default. */
static const uint64_t lut_delaysi[][2] = {
   { 0xe5e9f5fbe1c4551dULL, 0 }, /* Super Mario 64 60fps V2 */
};

static const char lut_audiosignal_id[][4] = {
   "NHT", /* Hydro Thunder */
   "NRK", /* Rugrats in Paris - The Movie */
   "NSO", /* NBA Showtime - NBA on NBC */
   "NTA", /* Disney's Tarzan */
};

static const struct cart_sidma_entry { char id[4]; unsigned char sidmaduration; } lut_sidmaduration_id[] = {
   { "NT6", 0x64 }, /* Tetris 64 */
};

/* Cartridge-ID keyed save-type database.
 *
 * Keyed on ROM header bytes 0x3B-0x3D (media format + 2-character game
 * code) plus, for a handful of titles, the region byte at 0x3E; rows
 * with a specific region must precede the wildcard row for the same
 * id.  This is the scheme EverDrive save databases use, so romhacks --
 * which change the header CRCs but keep the game code -- inherit the
 * base game's save hardware automatically.  Derived from ares'
 * mia/medium/nintendo-64.cpp (ISC licensed) save-type research. */
static const struct cart_save_entry { char id[4]; char region; unsigned char savetype; } lut_cart_save[] = {
   { "CDZ", 0  , SRAM        /* 96KiB unsupported; 32KiB attached */ }, /* Dezaemon 3D */
   { "CFZ", 0  , SRAM }, /* F-Zero X (J) */
   { "CLB", 0  , EEPROM_4KB }, /* Mario Party (NTSC) */
   { "CP2", 0  , FLASH_RAM }, /* Pocket Monsters Stadium 2 (J) */
   { "CPS", 0  , SRAM }, /* Pocket Monsters Stadium (J) */
   { "CZL", 0  , SRAM }, /* Legend of Zelda: Ocarina of Time [Zelda no Densetsu - Toki no Ocarina (J)] */
   { "N3D", 0  , EEPROM_16KB }, /* Doraemon 3: Nobita no Machi SOS! */
   { "N3H", 'J', SRAM }, /* Ganbare! Nippon! Olympics 2000 (J) */
   { "NA2", 0  , SRAM }, /* Virtual Pro Wrestling 2 */
   { "NAB", 0  , EEPROM_4KB }, /* Air Boarder 64 */
   { "NAD", 0  , EEPROM_4KB }, /* Worms Armageddon (U) */
   { "NAF", 0  , FLASH_RAM }, /* Doubutsu no Mori */
   { "NAG", 0  , EEPROM_4KB }, /* AeroGauge */
   { "NAL", 0  , SRAM }, /* Super Smash Bros. [Nintendo All-Star! Dairantou Smash Brothers (J)] */
   { "NB5", 0  , SRAM }, /* Biohazard 2 (J) */
   { "NB6", 0  , EEPROM_4KB }, /* Super B-Daman: Battle Phoenix 64 */
   { "NB7", 0  , EEPROM_16KB }, /* Banjo-Tooie [Banjo to Kazooie no Daiboken 2 (J)] */
   { "NBC", 0  , EEPROM_4KB }, /* Blast Corps */
   { "NBD", 0  , EEPROM_4KB }, /* Bomberman Hero [Mirian Ojo o Sukue! (J)] */
   { "NBH", 0  , EEPROM_4KB }, /* Body Harvest */
   { "NBK", 0  , EEPROM_4KB }, /* Banjo-Kazooie [Banjo to Kazooie no Daiboken (J)] */
   { "NBM", 0  , EEPROM_4KB }, /* Bomberman 64 [Baku Bomberman (J)] */
   { "NBN", 0  , EEPROM_4KB }, /* Bakuretsu Muteki Bangaioh */
   { "NBV", 0  , EEPROM_4KB }, /* Bomberman 64: The Second Attack! [Baku Bomberman 2 (J)] */
   { "NCC", 0  , FLASH_RAM }, /* Command & Conquer */
   { "NCG", 0  , EEPROM_4KB }, /* Choro Q 64 II - Hacha Mecha Grand Prix Race (J) */
   { "NCH", 0  , EEPROM_4KB }, /* Chopper Attack */
   { "NCK", 0  , FLASH_RAM }, /* NBA Courtside 2 featuring Kobe Bryant */
   { "NCR", 0  , EEPROM_4KB }, /* Penny Racers [Choro Q 64 (J)] */
   { "NCT", 0  , EEPROM_4KB }, /* Chameleon Twist */
   { "NCU", 0  , EEPROM_4KB }, /* Cruis'n USA */
   { "NCV", 0  , FLASH_RAM }, /* Cubivore [English translation/patch of Doubutsu Banchou (J)] */
   { "NCW", 0  , EEPROM_16KB }, /* Cruis'n World */
   { "NCX", 0  , EEPROM_4KB }, /* Custom Robo */
   { "NCZ", 0  , EEPROM_16KB }, /* Custom Robo V2 */
   { "ND2", 0  , EEPROM_16KB }, /* Doraemon 2: Nobita to Hikari no Shinden */
   { "ND3", 'J', EEPROM_16KB }, /* Akumajou Dracula Mokushiroku (J) */
   { "ND4", 'J', EEPROM_16KB }, /* Akumajou Dracula Mokushiroku Gaiden: Legend of Cornell (J) */
   { "ND6", 0  , EEPROM_16KB }, /* Densha de Go! 64 */
   { "NDA", 0  , FLASH_RAM }, /* Derby Stallion 64 */
   { "NDK", 'J', EEPROM_4KB }, /* Space Dynamites (J) [Dark Rift] */
   { "NDO", 0  , EEPROM_16KB }, /* Donkey Kong 64 */
   { "NDP", 0  , FLASH_RAM }, /* Dinosaur Planet (Unlicensed) */
   { "NDQ", 0  , EEPROM_4KB }, /* Disney's Donald Duck - Goin' Quackers [Quack Attack (E)] */
   { "NDR", 0  , EEPROM_4KB }, /* Doraemon: Nobita to 3tsu no Seireiseki */
   { "NDU", 0  , EEPROM_4KB }, /* Duck Dodgers starring Daffy Duck */
   { "NDY", 0  , EEPROM_4KB }, /* Diddy Kong Racing */
   { "NEA", 0  , EEPROM_4KB }, /* PGA European Tour */
   { "NEP", 0  , EEPROM_16KB }, /* Star Wars Episode I: Racer */
   { "NER", 0  , EEPROM_4KB }, /* Aero Fighters Assault [Sonic Wings Assault (J)] */
   { "NEV", 0  , EEPROM_16KB }, /* Neon Genesis Evangelion */
   { "NF2", 0  , EEPROM_4KB }, /* F-1 World Grand Prix II */
   { "NFG", 0  , EEPROM_4KB }, /* Fighter Destiny 2 */
   { "NFH", 0  , EEPROM_4KB }, /* In-Fisherman Bass Hunter 64 */
   { "NFU", 0  , EEPROM_16KB }, /* Conker's Bad Fur Day */
   { "NFW", 0  , EEPROM_4KB }, /* F-1 World Grand Prix */
   { "NFX", 0  , EEPROM_4KB }, /* Star Fox 64 [Lylat Wars (E)] */
   { "NFY", 0  , EEPROM_4KB }, /* Kakutou Denshou: F-Cup Maniax */
   { "NFZ", 0  , SRAM }, /* F-Zero X (U + E) */
   { "NG6", 0  , SRAM }, /* Ganmare Goemon: Dero Dero Douchuu Obake Tenkomori */
   { "NGC", 0  , EEPROM_16KB }, /* GT 64: Championship Edition */
   { "NGE", 0  , EEPROM_4KB }, /* GoldenEye 007 */
   { "NGL", 0  , EEPROM_4KB }, /* Getter Love!! */
   { "NGP", 0  , SRAM }, /* Goemon: Mononoke Sugoroku */
   { "NGT", 0  , EEPROM_16KB }, /* City Tour GrandPrix - Zen Nihon GT Senshuken */
   { "NGU", 0  , EEPROM_4KB }, /* Tsumi to Batsu: Hoshi no Keishousha (Sin and Punishment) */
   { "NGV", 0  , EEPROM_4KB }, /* Glover */
   { "NHA", 0  , EEPROM_4KB }, /* Bomberman 64: Arcade Edition (J) */
   { "NHF", 0  , EEPROM_4KB }, /* 64 Hanafuda: Tenshi no Yakusoku */
   { "NHP", 0  , EEPROM_4KB }, /* Heiwa Pachinko World 64 */
   { "NHY", 0  , SRAM }, /* Hybrid Heaven (J) */
   { "NIB", 0  , SRAM }, /* Itoi Shigesato no Bass Tsuri No. 1 Kettei Ban! */
   { "NIC", 0  , EEPROM_4KB }, /* Indy Racing 2000 */
   { "NIJ", 0  , EEPROM_4KB }, /* Indiana Jones and the Infernal Machine */
   { "NIM", 0  , EEPROM_16KB }, /* Ide Yosuke no Mahjong Juku */
   { "NIR", 0  , EEPROM_4KB }, /* Utchan Nanchan no Hono no Challenger: Denryuu Ira Ira Bou */
   { "NJ5", 0  , SRAM }, /* Jikkyou Powerful Pro Yakyuu 5 */
   { "NJF", 0  , FLASH_RAM }, /* Jet Force Gemini [Star Twins (J)] */
   { "NJG", 0  , SRAM }, /* Jinsei Game 64 */
   { "NJK", 0  , EEPROM_4KB }, /* Viewpoint 2064 (Master) */
   { "NJM", 0  , EEPROM_4KB }, /* Earthworm Jim 3D */
   { "NK2", 0  , EEPROM_4KB }, /* Snowboard Kids 2 [Chou Snobow Kids (J)] */
   { "NK4", 0  , EEPROM_16KB }, /* Kirby 64: The Crystal Shards (J rev>=2 + world) */
   { "NKA", 0  , EEPROM_4KB }, /* Fighters Destiny [Fighting Cup (J)] */
   { "NKG", 0  , SRAM }, /* Major League Baseball featuring Ken Griffey Jr. */
   { "NKI", 0  , EEPROM_4KB }, /* Killer Instinct Gold */
   { "NKJ", 0  , FLASH_RAM }, /* Ken Griffey Jr.'s Slugfest */
   { "NKT", 0  , EEPROM_4KB }, /* Mario Kart 64 */
   { "NLB", 0  , EEPROM_4KB }, /* Mario Party (PAL) */
   { "NLL", 0  , EEPROM_4KB }, /* Last Legion UX */
   { "NLR", 0  , EEPROM_4KB }, /* Lode Runner 3-D */
   { "NM6", 0  , FLASH_RAM }, /* Mega Man 64 */
   { "NM8", 0  , EEPROM_16KB }, /* Mario Tennis */
   { "NMF", 0  , SRAM }, /* Mario Golf 64 */
   { "NMG", 0  , EEPROM_4KB }, /* Monaco Grand Prix [Racing Simulation 2 (G)] */
   { "NMI", 0  , EEPROM_4KB }, /* Mission: Impossible */
   { "NML", 0  , EEPROM_4KB }, /* Mickey's Speedway USA [Mickey no Racing Challenge USA (J)] */
   { "NMO", 0  , EEPROM_4KB }, /* Monopoly */
   { "NMQ", 0  , FLASH_RAM }, /* Paper Mario */
   { "NMR", 0  , EEPROM_4KB }, /* Multi-Racing Championship */
   { "NMS", 0  , EEPROM_4KB }, /* Morita Shougi 64 */
   { "NMU", 0  , EEPROM_4KB }, /* Big Mountain 2000 */
   { "NMV", 0  , EEPROM_16KB }, /* Mario Party 3 */
   { "NMW", 0  , EEPROM_4KB }, /* Mario Party 2 */
   { "NMX", 0  , EEPROM_16KB }, /* Excitebike 64 */
   { "NMZ", 0  , EEPROM_4KB }, /* Zool - Majou Tsukai Densetsu (J) */
   { "NN6", 0  , EEPROM_4KB }, /* Dr. Mario 64 */
   { "NNA", 0  , EEPROM_4KB }, /* Star Wars Episode I: Battle for Naboo */
   { "NNB", 0  , EEPROM_16KB }, /* Kobe Bryant in NBA Courtside */
   { "NOB", 0  , SRAM }, /* Ogre Battle 64: Person of Lordly Caliber */
   { "NOS", 0  , EEPROM_4KB }, /* 64 Oozumou */
   { "NP2", 0  , EEPROM_4KB }, /* Chou Kuukan Night Pro Yakyuu King 2 (J) */
   { "NP3", 0  , FLASH_RAM }, /* Pokemon Stadium 2 [Pocket Monsters Stadium - Kin Gin (J)] */
   { "NP4", 0  , SRAM }, /* Jikkyou Powerful Pro Yakyuu 4 */
   { "NP6", 0  , SRAM }, /* Jikkyou Powerful Pro Yakyuu 6 */
   { "NPA", 0  , SRAM }, /* Jikkyou Powerful Pro Yakyuu 2000 */
   { "NPD", 0  , EEPROM_16KB }, /* Perfect Dark */
   { "NPE", 0  , SRAM }, /* Jikkyou Powerful Pro Yakyuu Basic Ban 2001 */
   { "NPF", 0  , FLASH_RAM }, /* Pokemon Snap [Pocket Monsters Snap (J)] */
   { "NPG", 0  , EEPROM_4KB }, /* Hey You, Pikachu! [Pikachu Genki Dechu (J)] */
   { "NPM", 0  , SRAM }, /* Premier Manager 64 */
   { "NPN", 0  , FLASH_RAM }, /* Pokemon Puzzle League */
   { "NPO", 0  , FLASH_RAM }, /* Pokemon Stadium */
   { "NPP", 0  , EEPROM_16KB }, /* Parlor! Pro 64: Pachinko Jikki Simulation Game */
   { "NPS", 0  , SRAM }, /* Jikkyou J.League 1999: Perfect Striker 2 */
   { "NPT", 0  , EEPROM_4KB }, /* Puyo Puyon Party */
   { "NPW", 0  , EEPROM_4KB }, /* Pilotwings 64 */
   { "NPY", 0  , EEPROM_4KB }, /* Puyo Puyo Sun 64 */
   { "NR7", 0  , EEPROM_16KB }, /* Robot Poncots 64: 7tsu no Umi no Caramel */
   { "NRA", 0  , EEPROM_4KB }, /* Rally '99 (J) */
   { "NRC", 0  , EEPROM_4KB }, /* Top Gear Overdrive */
   { "NRE", 0  , SRAM }, /* Resident Evil 2 */
   { "NRH", 0  , FLASH_RAM }, /* Rockman Dash - Hagane no Boukenshin (J) */
   { "NRI", 0  , SRAM }, /* New Tetris, The */
   { "NRS", 0  , EEPROM_4KB }, /* Star Wars: Rogue Squadron [Shutsugeki! Rogue Chuutai (J)] */
   { "NRZ", 0  , EEPROM_16KB }, /* Ridge Racer 64 */
   { "NS3", 0  , EEPROM_4KB }, /* AI Shougi 3 */
   { "NS4", 0  , SRAM }, /* Super Robot Taisen 64 */
   { "NS6", 0  , EEPROM_4KB }, /* Star Soldier: Vanishing Earth */
   { "NSA", 0  , EEPROM_4KB }, /* Sonic Wings Assault (J) */
   { "NSC", 0  , EEPROM_4KB }, /* Starshot: Space Circus Fever */
   { "NSI", 0  , SRAM }, /* Fushigi no Dungeon: Fuurai no Shiren 2 */
   { "NSM", 0  , EEPROM_4KB }, /* Super Mario 64 (+ Shindou Edition) */
   { "NSN", 0  , EEPROM_4KB }, /* Snow Speeder (J) */
   { "NSQ", 0  , FLASH_RAM }, /* StarCraft 64 */
   { "NSS", 0  , EEPROM_4KB }, /* Super Robot Spirits */
   { "NSU", 0  , EEPROM_4KB }, /* Rocket: Robot on Wheels */
   { "NSV", 0  , EEPROM_4KB }, /* Space Station Silicon Valley */
   { "NSW", 0  , EEPROM_4KB }, /* Star Wars: Shadows of the Empire [Teikoku no Kage (J)] */
   { "NT3", 0  , SRAM }, /* Shin Nihon Pro Wrestling - Toukon Road 2 - The Next Generation (J) */
   { "NT6", 0  , EEPROM_4KB }, /* Tetris 64 */
   { "NT9", 0  , FLASH_RAM }, /* Tigger's Honey Hunt */
   { "NTB", 0  , EEPROM_4KB }, /* Transformers: Beast Wars Metals 64 (J) */
   { "NTC", 0  , EEPROM_4KB }, /* 64 Trump Collection */
   { "NTE", 0  , SRAM }, /* 1080 Snowboarding */
   { "NTJ", 0  , EEPROM_4KB }, /* Tom & Jerry in Fists of Fury */
   { "NTM", 0  , EEPROM_4KB }, /* Mischief Makers [Yuke Yuke!! Trouble Makers (J)] */
   { "NTN", 0  , EEPROM_4KB }, /* All Star Tennis '99 */
   { "NTP", 0  , EEPROM_4KB }, /* Tetrisphere */
   { "NTR", 0  , EEPROM_4KB }, /* Top Gear Rally (J + E) */
   { "NTW", 0  , EEPROM_4KB }, /* 64 de Hakken!! Tamagotchi */
   { "NTX", 0  , EEPROM_4KB }, /* Taz Express */
   { "NUB", 0  , EEPROM_16KB }, /* PD Ultraman Battle Collection 64 */
   { "NUM", 0  , SRAM }, /* Nushi Zuri 64: Shiokaze ni Notte */
   { "NUT", 0  , SRAM }, /* Nushi Zuri 64 */
   { "NVB", 0  , SRAM }, /* Bass Rush - ECOGEAR PowerWorm Championship (J) */
   { "NVL", 0  , EEPROM_4KB }, /* V-Rally Edition '99 */
   { "NVP", 0  , SRAM }, /* Virtual Pro Wrestling 64 */
   { "NVY", 0  , EEPROM_4KB }, /* V-Rally Edition '99 (J) */
   { "NW2", 0  , SRAM }, /* WCW-nWo Revenge */
   { "NW4", 0  , FLASH_RAM }, /* WWF No Mercy */
   { "NWC", 0  , EEPROM_4KB }, /* Wild Choppers */
   { "NWL", 0  , SRAM }, /* Waialae Country Club: True Golf Classics */
   { "NWQ", 0  , EEPROM_4KB }, /* Rally Challenge 2000 */
   { "NWR", 0  , EEPROM_4KB }, /* Wave Race 64 (+ Shindou Edition) */
   { "NWT", 'J', EEPROM_4KB }, /* Wetrix (J) */
   { "NWU", 0  , EEPROM_4KB }, /* Worms Armageddon (E) */
   { "NWX", 0  , SRAM }, /* WWF WrestleMania 2000 */
   { "NXO", 0  , EEPROM_4KB }, /* Cruis'n Exotica */
   { "NYK", 0  , EEPROM_4KB }, /* Yakouchuu II: Satsujin Kouro */
   { "NYS", 0  , EEPROM_16KB }, /* Yoshi's Story */
   { "NYW", 0  , SRAM }, /* Harvest Moon 64 */
   { "NZL", 0  , SRAM }, /* Legend of Zelda: Ocarina of Time (E) */
   { "NZS", 0  , FLASH_RAM }, /* Legend of Zelda: Majora's Mask [Zelda no Densetsu - Mujura no Kamen (J)] */
};

/* CountPerOp overrides keyed on the cartridge ID, same scheme and
 * rationale as lut_cart_save above: one row per title instead of one
 * per release, and romhacks inherit the base game's timing.  Titles
 * without a stable retail cartridge ID (ALECK64 conversions, homebrew,
 * prototypes) and build-specific overrides (Wave Race 64 Shindou)
 * remain in the header-CRC table below. */
static const struct cart_cpop_entry { char id[4]; unsigned char cpop; } lut_cpop_id[] = {
   { "CLB", 1 }, /* Mario Party */
   { "N22", 1 }, /* Ready 2 Rumble Boxing - Round 2 */
   { "N2M", 1 }, /* Madden NFL 2002 */
   { "N3P", 1 }, /* Triple Play 2000 */
   { "N9M", 1 }, /* Madden NFL 99 */
   { "NAB", 1 }, /* Airboarder 64 */
   { "NB2", 1 }, /* NBA In the Zone '99 */
   { "NB4", 1 }, /* Bassmasters 2000 */
   { "NBH", 1 }, /* Body Harvest */
   { "NBQ", 3 }, /* BattleTanx - Global Assault */
   { "NBX", 3 }, /* BattleTanx */
   { "NBY", 1 }, /* Bug's Life, A */
   { "NCB", 1 }, /* Charlie Blast's Territory */
   { "NCD", 1 }, /* Carmageddon 64 */
   { "NCE", 1 }, /* Nuclear Strike 64 */
   { "NCL", 1 }, /* California Speed */
   { "NDE", 1 }, /* Destruction Derby 64 */
   { "NDO", 1 }, /* Donkey Kong 64 */
   { "NDQ", 3 }, /* Disney's Donald Duck - Goin' Quackers */
   { "NDU", 1 }, /* Duck Dodgers Starring Daffy Duck */
   { "NDZ", 1 }, /* Duke Nukem - ZER0 H0UR */
   { "NFD", 1 }, /* Flying Dragon */
   { "NFF", 1 }, /* Fighting Force 64 */
   { "NFH", 1 }, /* Bass Hunter 64 */
   { "NFL", 1 }, /* Madden NFL 2001 */
   { "NFQ", 1 }, /* Razor Freestyle Scooter */
   { "NFU", 3 }, /* Conker's Bad Fur Day */
   { "NGC", 1 }, /* GT 64 - Championship Edition */
   { "NGM", 1 }, /* Mystical Ninja 2 Starring Goemon */
   { "NGT", 1 }, /* City-Tour GP - Zennihon GT Senshuken */
   { "NHB", 1 }, /* Nintama Rantarou 64 Game Gallery */
   { "NHC", 1 }, /* Hercules - The Legendary Journeys */
   { "NHK", 1 }, /* Hiryuu no Ken Twin */
   { "NHS", 1 }, /* Hamster Monogatari 64 */
   { "NHT", 1 }, /* Hydro Thunder */
   { "NHX", 1 }, /* Hexen */
   { "NIB", 1 }, /* Shigesato Itoi's No. 1 Bass Fishing! Definitive Edition */
   { "NIJ", 1 }, /* Indiana Jones and the Infernal Machine */
   { "NIR", 1 }, /* Uchhannanchan no Hono no Challenger - Denryu IraIra Bou */
   { "NJ3", 1 }, /* Jikkyou World Soccer 3 */
   { "NJP", 1 }, /* International Superstar Soccer 64 */
   { "NKI", 1 }, /* Killer Instinct Gold */
   { "NKM", 1 }, /* Pro Mahjong Kiwame 64 */
   { "NLG", 3 }, /* LEGO Racers */
   { "NM3", 3 }, /* Monster Truck Madness 64 */
   { "NMD", 1 }, /* Madden NFL 2000 */
   { "NMO", 1 }, /* Monopoly */
   { "NMQ", 1 }, /* Mario Story */
   { "NMV", 1 }, /* Mario Party 3 */
   { "NMW", 1 }, /* Mario Party 2 */
   { "NMX", 1 }, /* Excitebike 64 */
   { "NNC", 1 }, /* Nightmare Creatures */
   { "NNR", 1 }, /* Pro Mahjong Tsuwamono 64 - Jansou Battle ni Chousen */
   { "NNS", 3 }, /* Beetle Adventure Racing! */
   { "NOS", 1 }, /* 64 Oozumou */
   { "NPA", 3 }, /* Jikkyou Powerful Pro Yakyuu - Basic Han 2001 */
   { "NPW", 3 }, /* Pilotwings 64 */
   { "NR2", 1 }, /* Rush 2 - Extreme Racing USA */
   { "NRO", 3 }, /* Road Rash 64 */
   { "NRR", 1 }, /* Roadsters Trophy */
   { "NRU", 1 }, /* San Francisco Rush 2049 */
   { "NSD", 1 }, /* Shadow Man */
   { "NSI", 1 }, /* Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou! */
   { "NSO", 1 }, /* NBA Showtime - NBA on NBC */
   { "NT9", 1 }, /* Tigger's Honey Hunt */
   { "NTA", 1 }, /* Disney's Tarzan */
   { "NTH", 1 }, /* Toy Story 2 */
   { "NTW", 1 }, /* 64 de Hakken!! Tamagotchi Minna de Tamagotchi World */
   { "NUT", 1 }, /* Nushi Tsuri 64 */
   { "NVB", 1 }, /* Bass Rush - ECOGEAR PowerWorm Championship */
   { "NVR", 1 }, /* Virtual Pool 64 */
   { "NW2", 1 }, /* WCW-nWo Revenge */
   { "NW3", 3 }, /* WCW Nitro */
   { "NWA", 1 }, /* War Gods */
   { "NWP", 1 }, /* Wipeout 64 */
   { "NWT", 3 }, /* Wetrix */
   { "NXF", 3 }, /* Xena Warrior Princess - The Talisman of Fate */
   { "NYK", 1 }, /* Yakouchuu II - Satsujin Kouro */
   { "NYW", 1 }, /* Harvest Moon 64 */
};

static const uint64_t lut_cpop[][2] = {
   { 0xD52FE29D8EA6A759ULL, 1 }, /* Donchan Puzzle Hanabi de Doon! (J) [ALECK64] */
   { 0x6D9D1FE484D10BEAULL, 1 }, /* Eleven Beat - World Tournament (J) [ALECK64] */
   { 0xB57D4EB4345E09E5ULL, 1 }, /* Guru - Kuru Kuru Fever (J) [ALECK64] */
   { 0x775AFA9C0EB52EF6ULL, 1 }, /* Hard Coded Demo by Silo and Fractal (PD) [a1] */
   { 0xFBB9F1FA6BF88689ULL, 1 }, /* Lt. Duck Dodgers (Prototype) */
   { 0xD5356BAC97AE69D2ULL, 1 }, /* Magical Tetris Challenge Featuring Mickey (J) [ALECK64] */
   { 0x315C74663A453265ULL, 1 }, /* Star Soldier - Vanishing Earth (J) [!] [ALECK64] */
   { 0xA3A044B56DB1BF5EULL, 1 }, /* Spacer by Memir (POM '99) (PD) */
   { 0x90AF8D2CE1AC1B37ULL, 1 }, /* Tower & Shaft (J) [ALECK64] */
   { 0x2F57C9F7F1E29CA6ULL, 1 }, /* Vivid Dolls (J) [ALECK64] */
};
