#ifndef M64P_UTIL_VERSION_H
#define M64P_UTIL_VERSION_H

#define CORE_VERSION_MAJOR 2
#define CORE_VERSION_MINOR 12
#define CORE_VERSION_PATCH 1

#define CVM_STRINGIFY(x) #x
#define CVM_VERSION_STRING(x,y,z) CVM_STRINGIFY(x) "." CVM_STRINGIFY(y) "." CVM_STRINGIFY(z)

#define CORE_VERSION_STRING CVM_VERSION_STRING(CORE_VERSION_MAJOR, CORE_VERSION_MINOR, CORE_VERSION_PATCH)

#endif
